options:
  image:
    type: string
    default: oaisoftwarealliance/oai-nr-ue:develop
    description: docker image name
  slu-port:
    type: int
    default: 2152
    description: slu port
  slc-port:
    type: int
    default: 36412
    description: slc-port
  x2c-port:
    type: int
    default: 36422
    description: x2c port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  rfsimulator:
    type: string
    default: "172.21.6.202"
    description: ip-address of gnb rf-sim. service name not accepted. shoul be match with gnb
  full-imsi:
    type: string
    default: "208990100001121"
    description: full imsi
  full-key:
    type: string
    default: "fec86ba6eb707ed08905757b1bb44b8f"
    description: full key
  opc:
    type: string
    default: "C42449363BBAD02B66D16BC975D77CC1"
    description: opc
  dnn:
    type: string
    default: oai
    description: dnn
  nssai-sst:
    type: int
    default: 1
    description: nssai sst
  nssai-sd:
    type: int
    default: 10203
    description: nssai sd
  use-additional-options:
    type: string
    default: "-E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod"
    description: use additional options
  # network attachment config
  multus-create:
    type: boolean
    default: true
    description: network attachment creation flag
  multus-ip:
    type: string
    default: "172.21.6.204"
    description: network attachment ip address
  multus-mask:
    type: string
    default: "22"
    description: network attachment net mask
  multus-gateway:
    type: string
    default: "172.21.7.254"
    description: network attachment gateway addr
  multus-host-interface:
    type: string
    default: "ens3"
    description: network attachment host interface name for master
