
imagePullPolicy: IfNotPresent
networks:
  pvCoreNetName: oai-private-core-net
  pvCoreNetSubnet: "192.168.68.0"
  pvCoreNetMask: "26"
  pubCoreNetName: oai-public-core-net
  pubCoreNetSubnet: "192.168.61.0"
  pubCoreNetMask: "26"

affinity:
  coreAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: worker
            operator: In
            values:
            - oai-core

cassandra:
  image: "cassandra"
  imageTag: "2.1"
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  probes:
    enabled: false
    params:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 10
  labels:
    app: cassandra-deployment
  networks:
    mainIfName: "eth1"
    mainIpAddr: "192.168.68.2"
    dbInitIfName: "eth1"
    dbInitIpAddr: "192.168.68.4"
  initContainer:
    image: "busybox"
    imageTag: "1.28"
    delayInit: 20
  service:
    name: cassandra-svc
    http1: 7000
    http2: 7001
    http3: 7199
    http4: 9160
    http5: 9042
    labels:
      app: cassandra-svc
  config:
    name: cassandra-db-init

oaiHss:
  image: "oaisoftwarealliance/oai-hss"
  imageTag: latest
  securityContext:
    privileged: true
  env:
    realm: "openairinterface.org"
    fqdn: "hss.openairinterface.org"
    prefix: "/openair-hss/etc"
    opKey: "1006020f0a478bf6b699f15c062e42b3"
    lteKey: "fec86ba6eb707ed08905757b1bb44b8f"
    apn1: "oai.ipv4"
    apn2: "internet"
    firstImsi: "208960100000001"
    nbUsers: "10"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
  probes:
    params:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 10
  labels:
    app: oai-hss-deployment
  networks:
    pvIfName: "eth1"
    pvIpAddr: "192.168.68.3"
    pubIfName: "eth2"
    pubIpAddr: "192.168.61.2"
  initContainer:
    image: "busybox"
    imageTag: "1.28"
    delayInit: 60
  service:
    name: oai-hss-svc
    labels:
      app: oai-hss-svc
    http1: 9042
    http2: 5868
    http3: 9080
    http4: 9081

redis:
  image: "redis"
  imageTag: "6.0.5"
  securityContext:
    privileged: true
  labels:
    app: redis-deployment
  networks:
    ifName: "eth1"
    ipAddr: "192.168.61.6"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
  probes:
    params:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 10
  service:
    name: redis-svc
    labels:
      app: redis-svc
    http1: 6380
  config:
    name: redis-conf

mme:
  image: "oaisoftwarealliance/magma-mme"
  imageTag: "latest"
  env:
    timeZone: Europe/Paris
    realm: openairinterface.org
    prefix: /openair-mme/etc
    hssHostName: hss
    hssFqdn: "hss.openairinterface.org"
    hssRealm: openairinterface.org
    mmeFqdn: mme.openairinterface.org
    features: mme_oai
  initContainer:
    image: "busybox"
    imageTag: "1.28"
    delayInit: 90
  securityContext:
    privileged: true
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
  probes:
    params:
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 10
    limits:
      memory: 512Mi
      cpu: 200m
  networks:
    IfName: "eth1"
    ipAddr: "192.168.61.3"
  labels:
    app: magma-mme-deployment
  service:
    name: magma-mme-svc
    labels:
      app: magma-mme-svc
    udp1: 2123
    http1: 3870
    http2: 5870
  config:
    entrypointName: mme-entrypoint
    confName: mme-config
    fdConfName: mme-fd-config