distributedMode: true
imagePullPolicy: IfNotPresent

networks:
  ## Core Private Network
  rfsim4gPrivateCoreNet: "192.168.68.0"
  rfsim4gPrivateCoreNetMask: "26"
  ## Core Private Network
  rfsim4gPublicCoreNet: "192.168.61.0"
  rfsim4gPublicCoreNetMask: "26"
  rfsim4gPublicCoreGateway: "192.168.61.1"
  ## Ran Private Network
  rfsim4gPrivateRanNet: "192.168.62.0"
  rfsim4gPrivateRanNetMask: "26"
  rfsim4gPrivateRanGateway: "192.168.62.1"
  ueNetName: oai-ue-net
  ueNetSubnet: "192.168.63.0"
  ueNetMask: "26"
  ueGateway: "192.168.63.1"
affinity:
  coreAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: worker
            operator: In
            values:
            - oai-core
  ranAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: worker
            operator: In
            values:
            - oai-ran

cassandra:
  image: "cassandra"
  imageTag: "2.1"
  resources:
    enabled: false
    requests:
      memory: 2Gi
      cpu: 2
    limits:
      memory: 2Gi
      cpu: 2
  networks:
    ipAddr: "192.168.68.2"
    dbInitIpAddr: "192.168.68.4"
  initContainer:
    delayInit: 10

oaiHss:
  image: "oaisoftwarealliance/oai-hss"
  imageTag: latest
  resources:
    enabled: false
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  labels:
    app: oai-hss-deployment
  networks:
    privateIpAddr: "192.168.68.3"
    publicIpAddr: "192.168.61.2"
  initContainer:
    delayInit: 30

redis:
  image: "redis"
  imageTag: "6.0.5"
  networks:
    ipAddr: "192.168.61.6"
  resources:
    enabled: false
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m

mme:
  image: "oaisoftwarealliance/magma-mme"
  imageTag: "latest"
  initContainer:
    delayInit: 30
  resources:
    enabled: false
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  networks:
    ipAddr: "192.168.61.3"

spgwc:
  image: "oaisoftwarealliance/oai-spgwc"
  imageTag: "latest"
  networks:
    ipAddr: "192.168.61.4"
  initContainer:
    delayInit: 30
  resources:
    enabled: false
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1

spgwu:
  image: "oaisoftwarealliance/oai-spgwu-tiny"
  imageTag: "latest"
  networks:
    ipAddr: "192.168.61.5"
  initContainer:
    delayInit: 30
  resources:
    enabled: false
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1

trfGen:
  image: oaisoftwarealliance/trf-gen-cn5g
  imageTag: focal
  networks:
    ipAddr: "192.168.61.11"
  initContainer:
    delayInit: 30
  resources:
    enabled: false
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m

flexran:
  enabled: false
  image: "ellior/flexranEnabledflexran"
  imageTag: "v1"
  securityContext:
    privileged: true
  resources:
    enabled: false
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1
  labels:
    app: flexran-deployment
  networks:
    ifName: "eth1"
    ipAddr: "192.168.61.61"
  initContainer:
    image: "busybox"
    imageTag: "1.28"
    delayInit: 140
  service:
    name: flexran-svc
    labels:
      app: flexran-svc
    http1: 9999
    http2: 2210
    http3: 5550
    http4: 6630
    metrics: 8000
  metrics:
    enabled: true
    image: "flexran-exporter"
    imageTag: "latest"
    statsPort: 9999
    resources:
      enabled: false
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 256Mi
        cpu: 200m
    probes:
      params:
        initialDelaySeconds: 10
        timeoutSeconds: 5

enb:
  enabled: true
  image: "oai-enb"
  imageTag: "develop"
  initContainer:
    delayInit: 90
  networks:
    ranIpAddr: "192.168.62.20"
    pubCoreIpAddr: "192.168.61.20"
    # brIpAddr: "192.168.40.2" # interface in node RAN that connected to ODL
  resources:
    enabled: false
    requests:
      memory: 3Gi
      cpu: 3
    limits:
      memory: 3Gi
      cpu: 3

ueCommons:
  image: "oai-lte-ue"
  imageTag: "develop"
  resources:
    enabled: false
    requests:
      memory: 2Gi
      cpu: 2
    limits:
      memory: 2Gi
      cpu: 2
ue:
  - name: ue0
    enabled: true
    port: 10001
    delayInit: 90
    env:
      shortImsi: "0100000001"
    networks:
      ranIpAddr: "192.168.62.30"
      ueIpAddr: "192.168.63.30"
      pubCoreIpAddr: "192.168.61.30"
  - name: ue1
    enabled: true
    port: 10001
    delayInit: 90
    env: 
      shortImsi: "0100000002"
    networks:
      ranIpAddr: "192.168.62.31"
      ueIpAddr: "192.168.63.32"
      pubCoreIpAddr: "192.168.61.32"
  - name: ue2
    enabled: true
    port: 10002
    delayInit: 90
    env: 
      shortImsi: "0100000003"
    networks:
      ifName: eth1
      ranIpAddr: "192.168.62.32"
      ueIpAddr: "192.168.63.32"
      pubCoreIpAddr: "192.168.61.32"
