apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  labels:
    chart: redis-6
{{ toYaml .Values.redis.service.labels | indent 4}}
spec:
  type: ClusterIP
  ports:
  - name: http1
    port: {{ .Values.redis.service.http1 }}
    targetPort: http1
    protocol: TCP
  selector:
{{ toYaml .Values.redis.labels | indent 4 }}