options:
  image:
    type: string
    default: rdefosseoai/oai-udm:latest
    description: docker image name
  http:
    type: int
    default: 80
    description: service http port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  instance:
    type: int
    default: 0
    description: instance id
  pid-directory:
    type: string
    default: /var/run
    description: pid directory
  udm-name:
    type: string
    default: OAI_UDM
    description: udm name
  sbi-if-name:
    type: string
    default: eth0
    description: sib interface name
  sbi-port:
    type: int
    default: 80
    description: sbi port
  sbi-http2-port:
    type: int
    default: 9090
    description: sbi http2 port
  udm-version-nb:
    type: string
    default: v1
    description: api version
  use-fqdn-dns:
    type: string
    default: "yes"
    description: use fqdn dns
  udr-ip-address:
    type: string
    default: oai-udr
    description: udr service address
  udr-port:
    type: int
    default: 80
    description: udr port
  udr-version-nb:
    type: string
    default: v1
    description: udr version nb
  udr-fqdn:
    type: string
    default: oai-udr
    description: udr fqdn
  nrf-ipv4-address:
    type: string
    default: oai-nrf
    description: nrf ipv4 address
  nrf-port:
    type: int
    default: 80
    description: nrf port
  nrf-api-version:
    type: string
    default: v1
    description: nrf api version
  nrf-fqdn:
    type: string
    default: oai-nrf
    description: nrf fqdn