options:
  image:
    type: string
    default: rdefosseoai/oai-smf:latest
    description: docker image name
  oai-smf:
    type: int
    default: 8805
    description: service udp port
  http1:
    type: int
    default: 80
    description: service http1 port
  http2:
    type: int
    default: 9090
    description: service http2 port
  time-zone:
    type: string
    default: "Europe/Paris"
  instance:
    type: int
    default: 0
    description: instance id
  pid-directory:
    type: string
    default: /var/run
    description: pid directory
  smf-interface-name-for-n4:
    type: string
    default: net1
    description: smf interface name for n4
  smf-interface-name-for-sbi:
    type: string
    default: eth0
    description: smf interface name for sbi
  smf-interface-port-for-sbi:
    type: int
    default: 80
    description: smf interface port for sbi
  smf-interface-http2-port-for-sbi:
    type: int
    default: 9090
    description: smf interface http2 port for sbi
  smf-api-version:
    type: string
    default: v1
    description: smf api version
  default-dns-ipv4-address:
    type: string
    default: "192.168.18.129"
    description: default dns ipv4 address
  default-dns-sec-ipv4-address:
    type: string
    default: "192.168.18.129"
    description: default dns sec ipv4 address
  amf-ipv4-address:
    type: string
    default: oai-amf
    description: amf ipv4 address
  amf-port:
    type: int
    default: 80
    description: amf port
  amf-api-version:
    type: string
    default: v1
    description: amf api version
  amf-fqdn:
    type: string
    default: oai-amf
    description: amf fqdn
  udm-ipv4-address:
    type: string
    default: oai-udm
    description: udm ipv4 address
  udm-port:
    type: int
    default: 80
    description: udm port
  udm-api-version:
    type: string
    default: v1
    description: udm api version
  udm-fqdn:
    type: string
    default: oai-udm
    description: udm fqdn
  upf-ipv4-address:
    type: string
    default: oai-spgwu
    description: upf ipv4 address
  upf-fqdn-0:
    type: string
    default: oai-spgwu
    description: upf fqdn 0
  nrf-ipv4-address:
    type: string
    default: oai-nrf
    description: nrf ipv4 address
  nrf-port:
    type: int
    default: 80
    description: nrf port
  nrf-api-version:
    type: string
    default: v1
    description: nrf api version
  use-local-subscription-info:
    type: string
    default: "yes"
    description: use local subscription info
  nrf-fqdn:
    type: string
    default: oai-nrf
    description: nrf fqdn
  register-nrf:
    type: string
    default: "yes"
    description: register nrf
  discover-upf:
    type: string
    default: "yes"
    description: discover upf
  use-fqdn-dns:
    type: string
    default: "yes"
    description: use fqdn dns
  dnn-range1:
    type: string
    default: "12.1.1.2 - 12.1.1.128"
    description: dnn range1
  dnn-range0:
    type: string
    default: "12.1.1.2 - 12.1.1.128"
    description: dnn range0
  dnn-ni1:
    type: string
    default: default
    description: dnn ni1
