options:
  image:
    type: string
    default: oaisoftwarealliance/oai-smf:v1.4.0
    description: docker image name
  oai-smf:
    type: int
    default: 8805
    description: service udp port
  http1:
    type: int
    default: 80
    description: service http1 port
  http2:
    type: int
    default: 9090
    description: service http2 port
  time-zone:
    type: string
    default: "Europe/Paris"
  instance:
    type: int
    default: 0
    description: instance id
  pid-directory:
    type: string
    default: /var/run
    description: pid directory
  smf-interface-name-for-n4:
    type: string
    default: eth0
    description: smf interface name for n4
  smf-interface-name-for-sbi:
    type: string
    default: eth0
    description: smf interface name for sbi
  smf-interface-port-for-sbi:
    type: int
    default: 80
    description: smf interface port for sbi
  smf-interface-http2-port-for-sbi:
    type: int
    default: 9090
    description: smf interface http2 port for sbi
  smf-api-version:
    type: string
    default: v1
    description: smf api version
  default-dns-ipv4-address:
    type: string
    default: "8.8.8.8"
    description: configure dns for ue. don't use k8s dns. it can be 8.8.8.8 or 4.4.4.4 if you don't know your dns.
  default-dns-sec-ipv4-address:
    type: string
    default: "8.8.8.8"
    description: configure dns for ue. don't use k8s dns. it can be 8.8.8.8 or 4.4.4.4 if you don't know your dns.
  amf-ipv4-address:
    type: string
    default: "oai-amf"
    description: amf ipv4 address
  amf-port:
    type: int
    default: 80
    description: amf port
  amf-api-version:
    type: string
    default: v1
    description: amf api version
  amf-fqdn:
    type: string
    default: oai-amf
    description: amf fqdn
  udm-ipv4-address:
    type: string
    default: "oai-udm"
    description: udm ipv4 address
  udm-port:
    type: int
    default: 80
    description: udm port
  udm-api-version:
    type: string
    default: v1
    description: udm api version
  udm-fqdn:
    type: string
    default: oai-udm
    description: udm fqdn
  upf-ipv4-address:
    type: string
    default: oai-spgwu
    description: upf ipv4 address
  upf-fqdn-0:
    type: string
    default: oai-spgwu
    description: upf fqdn 0
  nrf-ipv4-address:
    type: string
    default: "oai-nrf"
    description: nrf ipv4 address
  nrf-port:
    type: int
    default: 80
    description: nrf port
  nrf-api-version:
    type: string
    default: v1
    description: nrf api version
  use-local-subscription-info:
    type: string
    default: "yes"
    description: use local subscription info
  nrf-fqdn:
    type: string
    default: oai-nrf
    description: nrf fqdn
  register-nrf:
    type: string
    default: "yes"
    description: register nrf
  discover-upf:
    type: string
    default: "yes"
    description: discover upf
  use-fqdn-dns:
    type: string
    default: "yes"
    description: use fqdn dns
  http-version:
    type: int
    default: 1
    description: http version
  use-network-instance:
    type: string
    default: "no"
    description: use network instance
  domain-access:
    type: string
    default: "random"
    description: domain access
  domain-core:
    type: string
    default: "random"
    description: domain core
  enable-usae-reporting:
    type: string
    default: "no"
    description: enable usae reporting
  dnn-range0:
    type: string
    default: "12.1.1.2 - 12.1.1.40"
    description: dnn range0
  dnn-ni0:
    type: string
    default: oai.ipv4
    description: dnn ni0
  type0:
    type: string
    default: IPv4
    description: type 0
  nssai-sst0:
    type: int
    default: 1
    description: nssai sst0
  nssai-sd0:
    type: int
    default: 1
    description: nssai sd0
  type1:
    type: string
    default: IPv4
    description: type 1
  nssai-sst1:
    type: int
    default: 222
    description: nssai sst1
  nssai-sd1:
    type: int
    default: 123
    description: nssai sd1
  dnn-range1:
    type: string
    default: "12.1.1.41 - 12.1.1.80"
    description: dnn range1
  dnn-ni1:
    type: string
    default: default
    description: dnn ni1
  type2:
    type: string
    default: IPv4
    description: type 2
  nssai-sst2:
    type: int
    default: 1
    description: nssai sst2
  nssai-sd2:
    type: int
    default: 10203
    description: nssai sd2
  dnn-range2:
    type: string
    default: "12.1.1.81 - 12.1.1.120"
    description: dnn range2
  dnn-ni2:
    type: string
    default: oai
    description: dnn ni2