{{- if .Values.distributedMode }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: rfsim4g-ran-private
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "name": "rfsim4g-ran-private",
      "type": "bridge",
      "bridge": "ran-private",
      "isDefaultGateway": true,
      "ipam": {
        "type": "host-local",
        "subnet": {{- cat .Values.networks.rfsim4gPrivateRanNet "/" .Values.networks.rfsim4gPrivateRanNetMask | nospace | quote }}
      }
    }'
{{- end }}