{
 "title": "Base Station",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "SLAP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "BSconf_s1ap_connected" }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "BSconf_s1ap_pending" }
   ]
  },
  {
   "title": "MCC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BSconf_s1ap_mme_requested_plmns_mcc"
    }
   ]
  },
  {
   "title": "MNC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BSconf_s1ap_mme_requested_plmns_mnc"
    }
   ]
  },
  {
   "title": "MNC Length",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BSconf_s1ap_mme_requested_plmns_mnc_length"
    }
   ]
  },
  {
   "title": "MME Code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BSconf_s1ap_mme_served_gummeis_mme_code"
    }
   ]
  },
  {
   "title": "MME Group ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "BSconf_s1ap_mme_served_gummeis_mme_group_id"
    }
   ]
  },
  {
   "title": "MME REL Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "BSconf_s1ap_mme_rel_capacity" }
   ]
  },
  {
   "title": "Cell Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Carrier Index",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_carrier_index"
      }
     ]
    },
    {
     "title": "PUCCH Shift",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_deltaPUCCH_shift"
      }
     ]
    },
    {
     "title": "Antenna Ports",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_antenna_ports_count"
      }
     ]
    },
    {
     "title": "Duplex Mode",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_cell_config_duplex_mode" }
     ]
    },
    {
     "title": "Enable 64QM",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_enable_64QAM"
      }
     ]
    },
    {
     "title": "Eutra Band",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_cell_config_eutra_band" }
     ]
    },
    {
     "title": "Hopping Mode",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_hopping_mode"
      }
     ]
    },
    {
     "title": "NRB CQI",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_cell_config_nRB_cqi" }
     ]
    },
    {
     "title": "PDCCG OFDM SYM",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_init_nr_PDCCH_OFDM_sym"
      }
     ]
    },
    {
     "title": "MAC Connection Timer ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_mac_contention_resolution_timer"
      }
     ]
    },
    {
     "title": "Max HARQ TX",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_max_HARQ_Msg3Tx"
      }
     ]
    },
    {
     "title": "PUCCH AN",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_cell_config_n1PUCCH_AN" }
     ]
    },
    {
     "title": "N SB",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_cell_config_n_sb" }
     ]
    },
    {
     "title": "Phich",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_phich_duration",
       "legendFormat": "duration"
      },
      {
       "expr": "BSconf_cell_config_phich_resource",
       "legendFormat": "resource"
      }
     ]
    },
    {
     "title": "PUSCH Hopping Offset",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_pusch_hopping_offset"
      }
     ]
    },
    {
     "title": "Res Window Size",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_ra_response_window_size"
      }
     ]
    },
    {
     "title": "Window Length",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_si_config_si_window_length"
      }
     ]
    },
    {
     "title": "SIB1 Length",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_si_config_sib1_length"
      }
     ]
    },
    {
     "title": "PHY Cell ID",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_cell_config_phy_cell_id" }
     ]
    },
    {
     "title": "Prach",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_prach_config_index",
       "legendFormat": "index"
      },
      {
       "expr": "BSconf_cell_config_prach_freq_offset",
       "legendFormat": "freq"
      }
     ]
    },
    {
     "title": "SRS MAC UP PTS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_srs_mac_up_pts"
      }
     ]
    },
    {
     "title": "SRS Subframe",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_srs_subframe_config"
      }
     ]
    },
    {
     "title": "Subframe Assignment",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_subframe_assignment"
      }
     ]
    },
    {
     "title": "Subframe Assignment",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_subframe_assignment"
      }
     ]
    },
    {
     "title": "SIB1 Length",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_si_config_sib1_length"
      }
     ]
    },
    {
     "title": "SRS BW",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_cell_config_srs_bw_config"
      }
     ]
    },
    {
     "title": "Download Config",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "BSconf_cell_config_dl_bandwidth",
       "legendFormat": "bandwith"
      },
      {
       "expr": "BSconf_cell_config_dl_cyclic_prefix_length",
       "legendFormat": "prefix"
      },
      { "expr": "BSconf_cell_config_dl_freq", "legendFormat": "freq" },
      {
       "expr": "BSconf_cell_config_dl_pdsch_power",
       "legendFormat": "pusch power"
      }
     ]
    },
    {
     "title": "Upload Config",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "BSconf_cell_config_ul_bandwidth",
       "legendFormat": "bandwith"
      },
      {
       "expr": "BSconf_cell_config_ul_cyclic_prefix_length",
       "legendFormat": "prefix"
      },
      { "expr": "BSconf_cell_config_ul_freq", "legendFormat": "freq" },
      {
       "expr": "BSconf_cell_config_ul_pusch_power",
       "legendFormat": "pusch power"
      }
     ]
    },
    {
     "title": "Si SFN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "BSconf_cell_config_si_config_sfn",
       "legendFormat": "sfn"
      }
     ]
    }
   ]
  },
  {
   "title": "LC UE Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direction",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_lc_ue_config_lc_config_direction"
      }
     ]
    },
    {
     "title": "LCQ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_lc_ue_config_lc_config_lcg",
       "legendFormat": "LCG"
      }
     ]
    },
    {
     "title": "LCID",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_lc_ue_config_lc_config_lcid",
       "legendFormat": "LCG"
      }
     ]
    },
    {
     "title": "QCI",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_lc_ue_config_lc_config_qci",
       "legendFormat": "LCG"
      }
     ]
    },
    {
     "title": "QOS Type",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_lc_ue_config_lc_config_qos_bearer_type",
       "legendFormat": "LCG"
      }
     ]
    },
    {
     "title": "QOS Type",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_lc_ue_config_rnti", "legendFormat": "LCG" }
     ]
    }
   ]
  },
  {
   "title": "UE Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CQI Rep Mode",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_aperiodic_cqi_rep_mode"
      }
     ]
    },
    {
     "title": "Beta Offset Index",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_beta_offset_ACK_index",
       "legendFormat": "ACK"
      },
      {
       "expr": "BSconf_ue_config_beta_offset_CQI_index",
       "legendFormat": "CQI"
      },
      {
       "expr": "BSconf_ue_config_beta_offset_RI_index",
       "legendFormat": "RI"
      }
     ]
    },
    {
     "title": "Capabilities",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_capabilities_half_duplex",
       "legendFormat": "half duplex"
      },
      {
       "expr": "BSconf_ue_config_capabilities_intra_SF_hopping",
       "legendFormat": "SF"
      },
      {
       "expr": "BSconf_ue_config_capabilities_res_alloc_type1",
       "legendFormat": "Res Alloc"
      },
      {
       "expr": "BSconf_ue_config_capabilities_type2_sb_1",
       "legendFormat": "sb - 1"
      },
      {
       "expr": "BSconf_ue_config_capabilities_ue_category",
       "legendFormat": "ue category"
      }
     ]
    },
    {
     "title": "IMSI",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_ue_config_imsi" }
     ]
    },
    {
     "title": "Event A3",
     "type": "stat",
     "gridPos": { "h": 5, "w": 19, "x": 5, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_info_event_a3_a3_offset",
       "legendFormat": "offset"
      },
      {
       "expr": "BSconf_ue_config_info_event_a3_hysteresis",
       "legendFormat": "hysteresis"
      },
      {
       "expr": "BSconf_ue_config_info_event_a3_max_report_cells",
       "legendFormat": "max report cell"
      },
      {
       "expr": "BSconf_ue_config_info_event_a3_report_on_leave",
       "legendFormat": "report on leave"
      },
      {
       "expr": "BSconf_ue_config_info_event_a3_time_to_trigger",
       "legendFormat": "time to trigger"
      }
     ]
    },
    {
     "title": "Filter Coefficient",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_info_filter_coefficient_rsrp",
       "legendFormat": "rsrp"
      },
      {
       "expr": "BSconf_ue_config_info_filter_coefficient_rsrq",
       "legendFormat": "rsrq"
      }
     ]
    },
    {
     "title": "Offset Freq",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_info_offset_freq_neighbouring",
       "legendFormat": "neighbouring"
      },
      {
       "expr": "BSconf_ue_config_info_offset_freq_serving",
       "legendFormat": "serving"
      }
     ]
    },
    {
     "title": "Max HARQ TX",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_ue_config_max_HARQ_tx" }
     ]
    },
    {
     "title": "MEAS GAP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_meas_gap_config_pattern",
       "legendFormat": "config pattern"
      },
      {
       "expr": "BSconf_ue_config_meas_gap_config_sf_offset",
       "legendFormat": "sf offset"
      }
     ]
    },
    {
     "title": "Transmission Mode",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_transmission_mode"
      }
     ]
    },
    {
     "title": "TTI Bundling",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "BSconf_ue_config_tti_bundling" }
     ]
    },
    {
     "title": "Aggregated Bitrate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 8, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_ue_aggregated_max_bitrate_DL",
       "legendFormat": "download"
      },
      {
       "expr": "BSconf_ue_config_ue_aggregated_max_bitrate_UL",
       "legendFormat": "upload"
      }
     ]
    },
    {
     "title": "Transmission Antenna",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 15, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "BSconf_ue_config_ue_transmission_antenna"
      }
     ]
    }
   ]
  }
 ]
}