{
 "title": "UE statistics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RNTI",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "UEstatistics_rnti" }
     ]
    },
    {
     "title": "BSR",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "UEstatistics_bsr" }
     ]
    },
    {
     "title": "PHR",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "UEstatistics_phr" }
     ]
    }
   ]
  },
  {
   "title": "Download CQI Report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "P10 CSI",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_dl_cqi_report_csi_report_p10csi_wb_cqi"
      }
     ]
    },
    {
     "title": "RI",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_dl_cqi_report_csi_report_ri"
      }
     ]
    },
    {
     "title": "Serv Cell Index",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_dl_cqi_report_csi_report_serv_cell_index"
      }
     ]
    },
    {
     "title": "SFN SN",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_dl_cqi_report_sfn_sn"
      }
     ]
    }
   ]
  },
  {
   "title": "Upload CQI Report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CQI Serv Cell Index",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_ul_cqi_report_cqi_meas_serv_cell_index"
      }
     ]
    },
    {
     "title": "Pucch Serv Cell Index",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_ul_cqi_report_pucch_dbm_serv_cell_index"
      }
     ]
    },
    {
     "title": "Pucch DBM",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_ul_cqi_report_pucch_dbm_p0_pucch_dbm"
      }
     ]
    },
    {
     "title": "SFN SN",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_ul_cqi_report_sfn_sn"
      }
     ]
    }
   ]
  },
  {
   "title": "GTP Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAB ID",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_gtp_stats_e_rab_id"
      }
     ]
    },
    {
     "title": "TEID eNodeB",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_gtp_stats_teid_enb"
      }
     ]
    },
    {
     "title": "TEID SGW",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_gtp_stats_teid_sgw"
      }
     ]
    }
   ]
  },
  {
   "title": "MAC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "HARQ Round",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_mac_stats_harq_round"
      }
     ]
    },
    {
     "title": "Download LCID",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_mac_stats_mac_sdus_dl_lcid"
      }
     ]
    },
    {
     "title": "Download SDU Length",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_mac_stats_mac_sdus_dl_sdu_length"
      }
     ]
    },
    {
     "title": "PRB",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "UEstatistics_mac_stats_prb_ul", "legendFormat": "upload" },
      { "expr": "UEstatistics_mac_stats_prb_dl", "legendFormat": "download" }
     ]
    },
    {
     "title": "PRB Retx",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 15, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_mac_stats_prb_retx_ul",
       "legendFormat": "upload"
      },
      {
       "expr": "UEstatistics_mac_stats_prb_retx_dl",
       "legendFormat": "download"
      }
     ]
    },
    {
     "title": "TBS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "UEstatistics_mac_stats_tbs_ul", "legendFormat": "upload" },
      { "expr": "UEstatistics_mac_stats_tbs_dl", "legendFormat": "download" }
     ]
    },
    {
     "title": "MCS Download",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "UEstatistics_mac_stats_mcs1_dl", "legendFormat": "mcs1" },
      { "expr": "UEstatistics_mac_stats_mcs2_dl", "legendFormat": "mcs2" }
     ]
    },
    {
     "title": "MCS Upload",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "UEstatistics_mac_stats_mcs1_ul", "legendFormat": "mcs1" },
      { "expr": "UEstatistics_mac_stats_mcs2_ul", "legendFormat": "mcs2" }
     ]
    },
    {
     "title": "Total SDUC",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_mac_stats_total_bytes_sdus_ul",
       "legendFormat": "upload"
      },
      {
       "expr": "UEstatistics_mac_stats_total_bytes_sdus_dl",
       "legendFormat": "download"
      }
     ]
    },
    {
     "title": "Total PDU",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_mac_stats_total_pdu_ul",
       "legendFormat": "upload"
      },
      {
       "expr": "UEstatistics_mac_stats_total_pdu_dl",
       "legendFormat": "download"
      }
     ]
    },
    {
     "title": "Total PRB",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_mac_stats_total_prb_ul",
       "legendFormat": "upload"
      },
      {
       "expr": "UEstatistics_mac_stats_total_prb_dl",
       "legendFormat": "download"
      }
     ]
    },
    {
     "title": "Total TBS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "UEstatistics_mac_stats_total_tbs_ul",
       "legendFormat": "upload"
      },
      {
       "expr": "UEstatistics_mac_stats_total_tbs_dl",
       "legendFormat": "download"
      }
     ]
    }
   ]
  },
  { "title": "PDCP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "PKT RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "UEstatistics_pdcp_stats_pkt_rx", "legendFormat": "rx" },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_rx_aiat",
     "legendFormat": "rx-aiat"
    },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_rx_aiat_w",
     "legendFormat": "rx-aiat-w"
    },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_rx_oo",
     "legendFormat": "rx-oo"
    },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_rx_sn",
     "legendFormat": "rx-sn"
    },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_rx_w",
     "legendFormat": "rx-w"
    }
   ]
  },
  {
   "title": "PKT TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "UEstatistics_pdcp_stats_pkt_tx", "legendFormat": "tx" },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_tx_aiat",
     "legendFormat": "tx-aiat"
    },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_tx_aiat_w",
     "legendFormat": "tx-aiat-w"
    },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_tx_sn",
     "legendFormat": "tx-sn"
    },
    {
     "expr": "UEstatistics_pdcp_stats_pkt_tx_w",
     "legendFormat": "tx-w"
    }
   ]
  },
  {
   "title": "SFN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "UEstatistics_pdcp_stats_sfn", "legendFormat": "sfn" }
   ]
  },
  { "title": "RLC Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "TX Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "UEstatistics_rlc_report_tx_queue_hol_delay",
     "legendFormat": "hol delay"
    },
    {
     "expr": "UEstatistics_rlc_report_tx_queue_size",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "LC ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "UEstatistics_rlc_report_lc_id" }
   ]
  },
  {
   "title": "PDU Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UEstatistics_rlc_report_status_pdu_size"
    }
   ]
  },
  { "title": "RRC Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Meas ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UEstatistics_rrc_measurements_measid"
    }
   ]
  },
  {
   "title": "PCell",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UEstatistics_rrc_measurements_pcell_rsrp",
     "legendFormat": "rsrp"
    },
    {
     "expr": "UEstatistics_rrc_measurements_pcell_rsrq",
     "legendFormat": "rsrq"
    }
   ]
  },
  { "title": "SLAP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "ENB - UE SLAP ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UEstatistics_s1ap_stats_enb_ue_s1ap_id"
    }
   ]
  },
  {
   "title": "MME - UE SLAP ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UEstatistics_s1ap_stats_mme_ue_s1ap_id"
    }
   ]
  },
  {
   "title": "MCC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UEstatistics_s1ap_stats_selected_plmn_mcc"
    }
   ]
  },
  {
   "title": "MNC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UEstatistics_s1ap_stats_selected_plmn_mnc"
    }
   ]
  },
  {
   "title": "MNC Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UEstatistics_s1ap_stats_selected_plmn_mnc_length"
    }
   ]
  }
 ]
}