{{- if .Values.enb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enb
  labels:
    chart: enb
    app: enb
spec:
  selector:
    matchLabels:
      app: enb
  template:
    metadata:
      labels:
        app: enb
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {{- if .Values.distributedMode }}
          {
            "name": "rfsim4g-ran-private",
            "interface": "eth1",
            "ips": ["{{ .Values.enb.networks.ranIpAddr }}"],
            "default-route": ["{{ .Values.networks.rfsim4gPrivateRanGateway }}"]
          }
          {{- else }}
          {
            "name": "rfsim4g-core-public",
            "interface": "eth1",
            "ips": ["{{ .Values.enb.networks.pubCoreIpAddr }}"],
            "default-route": ["{{ .Values.networks.rfsim4gPublicCoreGateway }}"]
          }
          {{- end }}
        ]'
    spec:
      affinity:
      {{- if .Values.distributedMode }}
{{ toYaml .Values.affinity.ranAffinity | indent 8 }}
      {{- else }}
{{ toYaml .Values.affinity.coreAffinity | indent 8 }}
      {{- end }}
      initContainers:
        - name: init-core
          image: "busybox:1.28"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:  ['sh', '-c', "sleep {{ .Values.enb.initContainer.delayInit }}"]
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
      containers:
        - name: enb
          image: "{{ .Values.enb.image }}:{{ .Values.enb.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          ports:
            - name: udp1
              containerPort: 2152
              protocol: UDP
            - name: udp2
              containerPort: 36412
              protocol: UDP
            - name: udp3
              containerPort: 36422
              protocol: UDP
          env:
          - name: TZ
            value: Europe/Paris
          - name: USE_ADDITIONAL_OPTIONS
            value: --rfsim --log_config.global_log_options level,nocolor,time
          volumeMounts:
          - mountPath: /opt/oai-enb/etc/enb.conf
            name: enb-config
            subPath: enb.conf
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "pgrep lte-softmodem"
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "pgrep lte-softmodem"
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
          {{- if .Values.enb.resources.enabled }}
          resources:
            requests:
{{ toYaml .Values.enb.resources.requests | indent 14 }}
            limits:
{{ toYaml .Values.enb.resources.limits | indent 14 }}
          {{- end }}
      volumes:
      - configMap:
          defaultMode: 0664
          name: enb-config
        name: enb-config
{{- end }}
