apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: oai-ran-net
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "name": "oai-ran-net",
      "type": "bridge",
      "bridge": "oai-br",
      "isDefaultGateway": true,
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.62.0/26"
      }
    }'