options:
  image:
    type: string
    default: oaisoftwarealliance/oai-gnb:develop
    description: docker image name
  slu-port:
    type: int
    default: 2152
    description: slu port
  slc-port:
    type: int
    default: 36412
    description: slc-port
  x2c-port:
    type: int
    default: 36422
    description: x2c port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  rfsimulator:
    type: string
    default: server
    description: rf simulator
  use-sa-tdd-mono:
    type: string
    default: "yes"
    description: use sa tdd mono
  gnb-name:
    type: string
    default: gnb-rfsim
    description: gnb name
  mcc:
    type: int
    default: 208
    description: mcc
  mnc:
    type: int
    default: 99
    description: mnc
  mnc-length:
    type: int
    default: 2
    description: mnc length
  tac:
    type: int
    default: 1
    description: tac
  nssai-sst:
    type: int
    default: 1
    description: nssai sst
  nssai-sd0:
    type: string
    default: "0027db"
    description: nssai sd0
  nssai-sd1:
    type: int
    default: 112233
    description: nssai sd1
  amf-ip-address:
    type: string
    default: oai-amf
    description: amf ip address
  gnb-nga-if-name:
    type: string
    default: eth0
    description: gnb nga interface name
  gnb-nga-ip-address:
    type: string
    default: status.podIP
    description: gnb nga ip address
  gnb-ngu-if-name:
    type: string
    default: eth0
    description: gnb ngu interface name
  gnb-ngu-ip-address:
    type: string
    default: status.podIP
    description: gnb ngu ip address
  use-additional-option:
    type: string
    default: "--sa -E --rfsim"
    description: use additional option
