options:
  image:
    type: string
    default: oaisoftwarealliance/oai-gnb:develop
    description: docker image name
  slu-port:
    type: int
    default: 2152
    description: slu port
  slc-port:
    type: int
    default: 36412
    description: slc-port
  x2c-port:
    type: int
    default: 36422
    description: x2c port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  rfsimulator:
    type: string
    default: server
    description: rf simulator
  use-sa-tdd-mono:
    type: string
    default: "yes"
    description: use sa tdd mono
  gnb-name:
    type: string
    default: gnb-rfsim
    description: gnb name
  mcc:
    type: int
    default: 208
    description: mcc
  mnc:
    type: int
    default: 99
    description: mnc
  mnc-length:
    type: int
    default: 2
    description: mnc length
  tac:
    type: int
    default: 1
    description: tac
  nssai-sst:
    type: int
    default: 1
    description: nssai sst
  nssai-sd0:
    type: string
    default: "0027db"
    description: nssai sd0
  nssai-sd1:
    type: int
    default: 112233
    description: nssai sd1
  amf-ip-address:
    type: string
    default: "172.21.6.201"
    description: amf ip address. use oai-5g-mini-n1-net1
  gnb-nga-if-name:
    type: string
    default: net1
    description: gnb nga interface name. use eth0 if multus-create is false
  gnb-nga-ip-address:
    type: string
    default: "172.21.6.202"
    description: gnb nga ip address. oai-gnb-net1 ip addr
  gnb-ngu-if-name:
    type: string
    default: net2
    description: gnb ngu interface name. use eth0 if multus-create is false
  gnb-ngu-ip-address:
    type: string
    default: "172.21.6.203"
    description: gnb ngu ip address. oai-gnb-net2 ip addr
  use-additional-option:
    type: string
    default: "--sa -E --rfsim"
    description: use additional option
  # network attachment config
  multus-create:
    type: boolean
    default: true
    description: network attachment creation flag
  multus-ip1:
    type: string
    default: "172.21.6.202"
    description: network attachment ip address 1
  multus-mask1:
    type: string
    default: "22"
    description: network attachment net mask 1
  multus-ip2:
    type: string
    default: "172.21.6.203"
    description: network attachment ip address 2
  multus-mask2:
    type: string
    default: "22"
    description: network attachment net mask 2
  multus-gateway:
    type: string
    default: "172.21.7.254"
    description: network attachment gateway addr
  multus-host-interface:
    type: string
    default: "ens3"
    description: network attachment host interface name for master
