apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-spgwc-deployment
  labels:
    chart: oai-spgwc
{{ toYaml .Values.spgwc.labels | indent 4 }}
spec:
  selector:
    matchLabels:
{{ toYaml .Values.spgwc.labels | indent 6 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.spgwc.labels | indent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "{{ .Values.networks.pubCoreNetName }}",
            "interface": "{{ .Values.spgwc.networks.ifName }}",
            "ips": ["{{ .Values.spgwc.networks.ipAddr }}"],
            "default": true
          }
        ]'
    spec:
      affinity:
{{ toYaml .Values.affinity.coreAffinity | indent 8 }}
      initContainers:
        - name: init-magma
          image: "{{ .Values.spgwc.initContainer.image }}:{{ .Values.spgwc.initContainer.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:  ['sh', '-c', "sleep {{ .Values.spgwc.initContainer.delayInit }} && until nslookup {{ .Values.mme.service.name }}; do echo waiting for magma; sleep 2; done"]
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
      containers:
      - name: oai-spgwc
        image: "{{ .Values.spgwc.image }}:{{ .Values.spgwc.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        securityContext:
{{ toYaml .Values.spgwc.securityContext | indent 10 }}
        ports:
        - name: udp1
          containerPort: {{ .Values.spgwc.service.udp1 }}
          protocol: UDP
        - name: udp2
          containerPort: {{ .Values.spgwc.service.udp2 }}
          protocol: UDP
        env:
        - name: TZ
          value: {{ .Values.spgwc.env.timeZone }}
        - name: SGW_INTERFACE_NAME_FOR_S11
          value: {{ .Values.spgwc.env.sgwIfNameForS11 }}
        - name: PGW_INTERFACE_NAME_FOR_SX
          value: {{ .Values.spgwc.env.pgwIfNameForSx }}
        - name: DEFAULT_DNS_IPV4_ADDRESS
          value: "{{ .Values.spgwc.env.defaultDNS }}"
        - name: DEFAULT_DNS_SEC_IPV4_ADDRESS
          value: "{{ .Values.spgwc.env.defaultDNSSec }}"
        - name: PUSH_PROTOCOL_OPTION
          value: "{{ .Values.spgwc.env.pushProtocol }}"
        - name: APN_NI_1
          value: {{ .Values.spgwc.env.apnNI1 }}
        - name: APN_NI_2
          value: {{ .Values.spgwc.env.apnNI2 }}
        - name: DEFAULT_APN_NI_1
          value: {{ .Values.spgwc.env.defaultApnNI1 }}
        - name: UE_IP_ADDRESS_POOL_1
          value: "{{ .Values.spgwc.env.ueIpAddrPool1 }}"
        - name: UE_IP_ADDRESS_POOL_2
          value: "{{ .Values.spgwc.env.ueIpAddrPool2 }}"
        - name: MCC
          value: "{{ .Values.spgwc.env.mcc }}"
        - name: MNC
          value: "{{ .Values.spgwc.env.mnc }}"
        - name: MNC03
          value: "{{ .Values.spgwc.env.mnc03 }}"
        - name: TAC
          value: "{{ .Values.spgwc.env.tac }}"
        - name: GW_ID
          value: "{{ .Values.spgwc.env.gwID }}"
        - name: REALM
          value: {{ .Values.spgwc.env.realm }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep oai_spgwc"
{{ toYaml .Values.spgwc.probes.params | indent 10 }}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep oai_spgwc"
{{ toYaml .Values.spgwc.probes.params | indent 10 }}
        resources:
{{ toYaml .Values.spgwc.resources | indent 10 }}
