{{- range .Values.ue }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: oai-{{ .name }}-svc
  labels:
    chart: oai-ue
    app: oai-{{ .name }}-svc
spec:
  type: ClusterIP
  ports:
    - name: http1
      targetPort: http1
      port: {{ .port }}
      protocol: TCP
  selector:
    app: oai-{{ .name }}
---
{{- end }}
{{- end }}