options:
  image:
    type: string
    default: rdefosseoai/oai-udr:latest
    description: docker image name
  http1:
    type: int
    default: 80
    description: service http1 port
  http2:
    type: int
    default: 8080
    description: service http2 port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  instance:
    type: int
    default: 0
    description: instance id
  pid-directory:
    type: string
    default: /var/run
    description: pid directory
  udr-interface-name-for-nudr:
    type: string
    default: eth0
    description: udr interface name for nudr
  udr-interface-port-for-nudr:
    type: int
    default: 80
    description: udr interface port for nudr
  udr-interface-http2-port-for-nudr:
    type: int
    default: 8080
    description: sbi port
  udr-api-version:
    type: string
    default: v1
    description: api version
  mysql-ipv4-address:
    type: string
    default: mysql
    description: mysql service name
  mysql-user:
    type: string
    default: root
    description: mysql root user
  mysql-pass:
    type: string
    default: linux
    description: mysql root pass
  mysql-db:
    type: string
    default: oai_db
    description: mysql database name
  wait-mysql:
    type: int
    default: 120
    description: wait mysql
