options:
  image:
    type: string
    default: rdefosseoai/oai-amf:latest
    description: docker image name
  oai-amf:
    type: int
    default: 38412
    description: service sctp port
  http1:
    type: int
    default: 80
    description: service http1 port
  http2:
    type: int
    default: 9090
    description: service http2 port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  instance:
    type: int
    default: 0
    description: instance
  pid-directory:
    type: string
    default: /var/run
    description: pid directory
  mcc:
    type: int
    default: 208
    description: mcc
  mnc:
    type: int
    default: 95
    description: mnc
  region-id:
    type: int
    default: 128
    description: region id
  amf-set-id:
    type: int
    default: 1
    description: amf set id
  served-guami-mcc-0:
    type: int
    default: 208
    description: served guami mcc 0
  served-guami-mnc-0:
    type: int
    default: 95
    description: served guami mnc 0
  served-guami-region-id-0:
    type: int
    default: 128
    description: served guami region id 0
  served-guami-amf-set-id-0:
    type: int
    default: 1
    description: served guami amf set id 0
  served-guami-mcc-1:
    type: int
    default: 460
    description: served guami mcc 1
  served-guami-mnc-1:
    type: int
    default: 11
    description: served guami mnc 1
  served-guami-region-id-1:
    type: int
    default: 10
    description: served guami region id 1
  served-guami-amf-set-id-1:
    type: int
    default: 1
    description: served guami amf set id 1
  plmn-support-mcc:
    type: int
    default: 208
    description: plmn support mcc
  plmn-support-mnc:
    type: int
    default: 95
    description: plmn support mnc
  plmn-support-tac:
    type: string
    default: "0x0001"
    description: plmn support tac
  sst-0:
    type: int
    default: 1
    description: sst 0
  sd-0:
    type: int
    default: 1
    description: sd 0
  sst-1:
    type: int
    default: 111
    description: sst 1
  sd-1:
    type: int
    default: 124
    description: sd 1
  sst-2:
    type: int
    default: 2
    description: sst 2
  sd-2:
    type: int
    default: 2
    description: sd 2
  amf-interface-name-for-ngap:
    type: string
    default: eth0
    description: amf interface name for ngap
  amf-interface-name-for-n11:
    type: string
    default: eth0
    description: amf interface name for n11
  smf-instance-id-0:
    type: int
    default: 1
    description: smf instance id 0
  smf-fqdn-0:
    type: string
    default: oai-smf
    description: smf fqdn 0
  smf-ipv4-addr-0:
    type: string
    default: oai-smf
    description: smf ipv4 addr 0
  smf-http-version-0:
    type: string
    default: v1
    description: smf http version 0
  selected-0:
    type: boolean
    default: true
    description: slected 0
  smf-instance-id-1:
    type: int
    default: 2
    description: smf instance id 1
  smf-fqdn-1:
    type: string
    default: localhost
    description: smf fqdn 1
  smf-ipv4-addr-1:
    type: string
    default: oai-smf
    description: smf ipv4 addr 1
  smf-http-version-1:
    type: string
    default: v1
    description: smf http version 1
  selected-1:
    type: boolean
    default: false
    description: selected 1
  mysql-server:
    type: string
    default: mysql
    description: mysql server
  mysql-user:
    type: string
    default: root
    description: mysql user
  mysql-pass:
    type: string
    default: linux
    description: mysql pass
  mysql-db:
    type: string
    default: oai_db
    description: mysql database
  operator-key:
    type: string
    default: c42449363bbad02b66d16bc975d77cc1
    description: operator key
  nrf-ipv4-address:
    type: string
    default: oai-nrf
    description: nrf ipv4 address
  nrf-port:
    type: int
    default: 80
    description: nrf port
  nf-registration:
    type: string
    default: "yes"
    description: nf registration
  smf-selection:
    type: string
    default: "yes"
    description: smf selection
  use-fqdn-dns:
    type: string
    default: "yes"
    description: use fqdn dns
  external-ausf:
    type: string
    default: "yes"
    description: external ausf
  nrf-api-version:
    type: string
    default: v1
    description: smf selection
  nrf-fqdn:
    type: string
    default: oai-nrf
    description: nrf fqdn
  ausf-ipv4-address:
    type: string
    default: oai-ausf
    description: ausf ipv4 address
  ausf-port:
    type: int
    default: 80
    description: ausf port
  ausf-fqdn:
    type: string
    default: oai-ausf
    description: ausf fqdn
  ausf-api-version:
    type: string
    default: v1
    description: ausf api version
  nssf-ipv4-address:
    type: string
    default: oai-nssf
    description: nssf ipv4 address
  nssf-fqdn:
    type: string
    default: oai-nssf
    description: nssf fqdn
  nssf-port:
    type: int
    default: 80
    description: nssf port
  nssf-api-version:
    type: string
    default: v1
    description: nssf api version
  external-udm:
    type: string
    default: "no"
    description: external udm
  use-http2:
    type: string
    default: "no"
    description: use http2
  int-algo-list:
    type: string
    default: '[ "NIA0" , "NIA1" , "NIA2" ]'
    description: int algo list
  ciph-algo-list:
    type: string
    default: '[ "NEA0" , "NEA1" , "NEA2" ]'
    description: cipg algo list
