apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-spgwu-deployment
  labels:
    chart: oai-spgwu
{{ toYaml .Values.spgwu.labels | indent 4 }}
spec:
  selector:
    matchLabels:
{{ toYaml .Values.spgwu.labels | indent 6 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.spgwu.labels | indent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "{{ .Values.networks.pubCoreNetName }}",
            "interface": "{{ .Values.spgwu.networks.ifName }}",
            "ips": ["{{ .Values.spgwu.networks.ipAddr }}"],
            "default": true
          }
        ]'
    spec:
      affinity:
{{ toYaml .Values.affinity.coreAffinity | indent 8 }}
      initContainers:
        - name: init-spgwc
          image: "{{ .Values.spgwu.initContainer.image }}:{{ .Values.spgwu.initContainer.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:  ['sh', '-c', "sleep {{ .Values.spgwu.initContainer.delayInit }} && until nslookup {{ .Values.spgwc.service.name }}; do echo waiting for spgwc; sleep 2; done"]
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
      containers:
      - name: oai-spgwu
        image: "{{ .Values.spgwu.image }}:{{ .Values.spgwu.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        securityContext:
{{ toYaml .Values.spgwc.securityContext | indent 10 }}
        ports:
        - name: udp1
          containerPort: {{ .Values.spgwu.service.udp1 }}
          protocol: UDP
        - name: udp2
          containerPort: {{ .Values.spgwu.service.udp2 }}
          protocol: UDP
        env:
        - name: TZ
          value: {{ .Values.spgwu.env.timeZone }}
        - name: PID_DIRECTORY
          value: {{ .Values.spgwu.env.pidDir }}
        - name: INSTANCE
          value: "{{ .Values.spgwu.env.instance }}"
        - name: SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP
          value: {{ .Values.spgwu.env.sgwIfNameForS1uS12S4 }}
        - name: PGW_INTERFACE_NAME_FOR_SGI
          value: {{ .Values.spgwu.env.pgwIfNameForSgi }}
        - name: SGW_INTERFACE_NAME_FOR_SX
          value: {{ .Values.spgwu.env.sgwIfNameForSx }}
        - name: SPGWC0_IP_ADDRESS
          value: "{{ .Values.spgwc.networks.ipAddr }}"
        - name: NETWORK_UE_IP
          value: "{{ .Values.spgwu.env.netUeIP }}"
        - name: NETWORK_UE_NAT_OPTION
          value: "{{ .Values.spgwu.env.netUeNAT }}"
        - name: MCC
          value: "{{ .Values.spgwu.env.mcc }}"
        - name: MNC
          value: "{{ .Values.spgwu.env.mnc }}"
        - name: MNC03
          value: "{{ .Values.spgwu.env.mnc03 }}"
        - name: TAC
          value: "{{ .Values.spgwu.env.tac }}"
        - name: GW_ID
          value: "{{ .Values.spgwu.env.gwID }}"
        - name: REALM
          value: {{ .Values.spgwu.env.realm }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep oai_spgwu"
{{ toYaml .Values.spgwu.probes.params | indent 10 }}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep oai_spgwu"
{{ toYaml .Values.spgwu.probes.params | indent 10 }}
        resources:
{{ toYaml .Values.spgwc.resources | indent 10 }}
