apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-spgwu
  labels:
    chart: oai-spgwu
    app: oai-spgwu
spec:
  selector:
    matchLabels:
      app: oai-spgwu
  template:
    metadata:
      labels:
        app: oai-spgwu
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "rfsim4g-core-public",
            "interface": "eth1",
            "ips": ["{{ .Values.spgwu.networks.ipAddr }}"],
            "default": true
          }
        ]'
    spec:
      affinity:
{{ toYaml .Values.affinity.coreAffinity | indent 8 }}
      initContainers:
        - name: init-spgwc
          image: "busybox:1.28"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:  ['sh', '-c', "sleep {{ .Values.spgwu.initContainer.delayInit }} && until nslookup oai-spgwc-svc; do echo waiting for spgwc; sleep 2; done"]
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
      containers:
      - name: oai-spgwu
        image: "{{ .Values.spgwu.image }}:{{ .Values.spgwu.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        ports:
        - name: udp1
          containerPort: 2152
          protocol: UDP
        - name: udp2
          containerPort: 8805
          protocol: UDP
        env:
        - name: TZ
          value: Europe/Paris
        - name: PID_DIRECTORY
          value: /var/run
        - name: INSTANCE
          value: "1"
        - name: SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP
          value: eth1
        - name: PGW_INTERFACE_NAME_FOR_SGI
          value: eth1
        - name: SGW_INTERFACE_NAME_FOR_SX
          value: eth1
        - name: SPGWC0_IP_ADDRESS
          value: "{{ .Values.spgwc.networks.ipAddr }}"
        - name: NETWORK_UE_IP
          value: "12.0.0.0/24"
        - name: NETWORK_UE_NAT_OPTION
          value: "yes"
        - name: MCC
          value: "208"
        - name: MNC
          value: "96"
        - name: MNC03
          value: "096"
        - name: TAC
          value: "1"
        - name: GW_ID
          value: "1"
        - name: REALM
          value: openairinterface.org
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep oai_spgwu"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep oai_spgwu"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        {{- if .Values.spgwu.resources.enabled }}
        resources:
          requests:
{{ toYaml .Values.spgwu.resources.requests | indent 12 }}
          limits:
{{ toYaml .Values.spgwu.resources.limits | indent 12 }}
        {{- end }}