apiVersion: apps/v1
kind: Deployment
metadata:
  name: trf-gen-deployment
  labels:
    chart: trf-gen
{{ toYaml .Values.trfGen.labels | indent 4 }}
spec:
  selector:
    matchLabels:
{{ toYaml .Values.trfGen.labels | indent 6 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.trfGen.labels | indent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "{{ .Values.networks.pubCoreNetName }}",
            "interface": "{{ .Values.trfGen.networks.ifName }}",
            "ips": ["{{ .Values.trfGen.networks.ipAddr }}"],
            "default": true
          }
        ]'
    spec:
      affinity:
{{ toYaml .Values.affinity.coreAffinity | indent 8 }}
      initContainers:
        - name: init-spgwu
          image: "{{ .Values.trfGen.initContainer.image }}:{{ .Values.trfGen.initContainer.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:  ['sh', '-c', "sleep {{ .Values.spgwc.initContainer.delayInit }} && until nslookup {{ .Values.spgwu.service.name }}; do echo waiting for spgwu; sleep 2; done"]
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
      containers:
      - name: trg-gen
        securityContext:
{{ toYaml .Values.trfGen.securityContext | indent 10 }}
        image: "{{ .Values.trfGen.image }}:{{ .Values.trfGen.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        command:
        - /bin/bash
        - -c
        - "ip route add {{ .Values.spgwu.env.netUeIP }} via {{ .Values.spgwu.networks.ipAddr }} dev eth1; sleep infinity"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "ping -c 2 {{ .Values.spgwu.networks.ipAddr }}"
{{ toYaml .Values.trfGen.probes.params | indent 10 }}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "ping -c 2 {{ .Values.spgwu.networks.ipAddr }}"
{{ toYaml .Values.trfGen.probes.params | indent 10 }}
        resources:
{{ toYaml .Values.trfGen.resources | indent 10 }}
