apiVersion: apps/v1
kind: Deployment
metadata:
  name: trf-gen
  labels:
    chart: trf-gen
    app: trf-gen
spec:
  selector:
    matchLabels:
      app: trf-gen
  template:
    metadata:
      labels:
        app: trf-gen
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "rfsim4g-core-public",
            "interface": "eth1",
            "ips": ["{{ .Values.trfGen.networks.ipAddr }}"],
            "default": true
          }
        ]'
    spec:
      affinity:
{{ toYaml .Values.affinity.coreAffinity | indent 8 }}
      initContainers:
        - name: init-spgwu
          image: "busybox:1.28"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:  ['sh', '-c', "sleep {{ .Values.trfGen.initContainer.delayInit }} && until nslookup oai-spgwu-svc; do echo waiting for spgwu; sleep 2; done"]
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
      containers:
      - name: trg-gen
        securityContext:
          privileged: true
        image: "{{ .Values.trfGen.image }}:{{ .Values.trfGen.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        command:
        - /bin/bash
        - -c
        - "ip route add 12.0.0.0/24 via {{ .Values.spgwu.networks.ipAddr }} dev eth1; sleep infinity"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "ping -c 2 {{ .Values.spgwu.networks.ipAddr }}"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "ping -c 2 {{ .Values.spgwu.networks.ipAddr }}"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 10
          {{- if .Values.trfGen.resources.enabled }}
        resources:
          requests:
{{ toYaml .Values.trfGen.resources.requests | indent 12 }}
          limits:
{{ toYaml .Values.trfGen.resources.limits | indent 12 }}
        {{- end }}