apiVersion: apps/v1
kind: Deployment
metadata:
  name: magma-mme-deployment
  labels:
    chart: magma-mme
{{ toYaml .Values.mme.labels | indent 4 }}
spec:
  selector:
    matchLabels:
{{ toYaml .Values.mme.labels | indent 6 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.mme.labels | indent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "{{ .Values.networks.pubCoreNetName }}",
            "interface": "{{ .Values.mme.networks.ifName }}",
            "ips": ["{{ .Values.mme.networks.ipAddr }}"],
            "default": true
          }
        ]'
    spec:
      affinity:
{{ toYaml .Values.affinity.coreAffinity | indent 8 }}
      initContainers:
        - name: init-hss
          image: "{{ .Values.mme.initContainer.image }}:{{ .Values.mme.initContainer.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:  ['sh', '-c', "sleep {{ .Values.mme.initContainer.delayInit }} && until nslookup {{ .Values.oaiHss.service.name }}; do echo waiting for oai-hss; sleep 2; done"]
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
        - name: init-redis
          image: "{{ .Values.mme.initContainer.image }}:{{ .Values.mme.initContainer.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:  ['sh', '-c', "until nslookup {{ .Values.redis.service.name }}; do echo waiting for redis; sleep 2; done"]
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
      containers:
      - name: magma-mme
        image: "{{ .Values.mme.image }}:{{ .Values.mme.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        securityContext:
{{ toYaml .Values.mme.securityContext | indent 10 }}
        ports:
        - name: udp1
          containerPort: {{ .Values.mme.service.udp1 }}
          protocol: UDP
        - name: http1
          containerPort: {{ .Values.mme.service.http1 }}
          protocol: TCP
        - name: http2
          containerPort: {{ .Values.mme.service.http2 }}
          protocol: TCP
        command:
        - /bin/bash
        - -c
        - "/magma-mme/bin/entrypoint.sh"
        env:
        - name: TZ
          value: {{ .Values.mme.env.timeZone }}
        - name: REALM
          value: {{ .Values.mme.env.realm }}
        - name: PREFIX
          value: {{ .Values.mme.env.prefix }}
        - name: HSS_HOSTNAME
          value: {{ .Values.mme.env.hssHostName }}
        - name: HSS_FQDN
          value: "{{ .Values.mme.env.hssFqdn }}"
        - name: HSS_REALM
          value: {{ .Values.mme.env.hssRealm }}
        - name: MME_FQDN
          value: {{ .Values.mme.env.mmeFqdn }}
        - name: FEATURES
          value: {{ .Values.mme.env.features }}
        volumeMounts:
        - name: mme-entrypoint
          mountPath: /magma-mme/bin/entrypoint.sh
          subPath: entrypoint.sh
        - name: mme-config
          mountPath: /magma-mme/etc/mme.conf
          subPath: mme.conf
        - name: mme-fd-config
          mountPath: /magma-mme/etc/mme_fd.conf.tmplt
          subPath: mme_fd.conf.tmplt
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep oai_mme"
{{ toYaml .Values.mme.probes.params | indent 10 }}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep oai_mme"
{{ toYaml .Values.mme.probes.params | indent 10 }}
        {{- if .Values.mme.resources.enabled }}
        resources:
          requests:
{{ toYaml .Values.mme.resources.requests | indent 12 }}
          limits:
{{ toYaml .Values.mme.resources.limits | indent 12 }}
        {{- end }}
      volumes:
      - name: mme-config
        configMap:
          name: {{ .Values.mme.config.confName }}
      - name: mme-fd-config
        configMap:
          name: {{ .Values.mme.config.fdConfName }}
      - name: mme-entrypoint
        configMap:
          name: {{ .Values.mme.config.entrypointName }}
          defaultMode: 0774
