apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: oai
  labels:
    app: redis-deployment
    chart: redis-6
spec:
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "public-net",
            "interface": "eth1",
            "ips": ["192.168.61.6"],
            "default": true
          }
        ]'
    spec:
      containers:
      - name: redis
        image: "redis:6.0.5"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
          - name: http1
            containerPort: 6380
            protocol: TCP
        command:
        - /bin/bash
        - -c 
        - "redis-server /usr/local/etc/redis/redis.conf"
        volumeMounts:
        - name: redis-conf
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "redis-cli -h 192.168.61.6 -p 6380 ping"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "redis-cli -h 192.168.61.6 -p 6380 ping"
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 100m
      volumes:
      - name: redis-conf
        configMap:
          name: redis-conf

