apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis-svc
    chart: redis-6
spec:
  type: ClusterIP
  ports:
  - name: http1
    port: 6380
    targetPort: http1
    protocol: TCP
  selector:
    app: redis-deployment