options:
  image:
    type: string
    default: oaisoftwarealliance/oai-spgwu-tiny:latest
    description: spgwc image name
  udp1-port:
    type: int
    default: 2152
    description: udp1 container port
  udp2-port:
    type: int
    default: 8805
    description: udp2 container port
  # env config
  tz:
    type: string
    default: Europe/Paris
    description: time znoe
  pid-directory:
    type: string
    default: /var/run
    description: pid dir
  instance:
    type: string
    default: "1"
    description: pid dir
  sgw-interface-name-for-s1u:
    type: string
    default: eth1
    description: sgw interface name for s1u
  pgw-interface-name-for-sgi:
    type: string
    default: eth1
    description: pgw interface name for sgi
  sgw-interface-name-for-sx:
    type: string
    default: eth1
    description: sgw interface name for sx
  spgwc0-ip-addr:
    type: string
    default: "192.168.61.4"
    description: spgwc ip addr
  network-ue-ip:
    type: string
    default: "12.0.0.0/24"
    description: network ue ip
  network-ue-nat-option:
    type: string
    default: "yes"
    description: network ue nat option
  mcc:
    type: string
    default: "208"
    description: mcc
  mnc:
    type: string
    default: "96"
    description: mnc
  mnc03:
    type: string
    default: "096"
    description: mnc03
  tac:
    type: string
    default: "1"
    description: tac
  gw-id:
    type: string
    default: "1"
    description: gw id
  realm:
    type: string
    default: "openairinterface.org"
    description: realm
  # network config
  net-name:
    type: string
    default: "public-net"
    description: network name
  interface:
    type: string
    default: "eth1"
    description: service interface name
  ip-addr:
    type: string
    default: "192.168.61.5"
    description: service ip addr