options:
  image:
    type: string
    default: rdefosseoai/oai-ausf:latest
    description: docker image name
  http:
    type: int
    default: 80
    description: service http port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  instance-id:
    type: int
    default: 0
    description: instance id
  pid-dir:
    type: string
    default: /var/run
    description: pid directory
  ausf-name:
    type: string
    default: OAI_AUSF
    description: ausf name
  sbi-if-name:
    type: string
    default: eth0
    description: sbi if name
  sbi-port:
    type: int
    default: 80
    description: sbi port
  use-fqdn-dns:
    type: string
    default: "yes"
    description: use fqdn dns
  udm-ip-address:
    type: string
    default: oai-udm
    description: oai udm addr
  udm-port:
    type: int
    default: 80
    description: udm port
  udm-version-nb:
    type: string
    default: v1
    description: udm version
  udm-fqdn:
    type: string
    default: oai-udm
    description: udm fqdn
