# Copyright 2022 Ubuntu
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  image:
    type: string
    default: rdefosseoai/oai-ausf:latest
    description: docker image name
  http:
    type: int
    default: 80
    description: service http port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  instance-id:
    type: int
    default: 0
    description: instance id
  pid-id:
    type: string
    default: /var/run
    description: pid id
  ausf-name:
    type: string
    default: OAI_AUSF
    description: ausf name
  sbi-if-name:
    type: string
    default: eth0
    description: sbi if name
  sbi-port:
    type: string
    default: 80
    description: sbi port
  use-fqdn-dns:
    type: string
    default: yes
    description: use fqdn dns
  udm-ip-address:
    type: string
    default: oai-udm
    description: oai udm addr
  udm-port:
    type: int
    default: 80
    description: udm port
  udm-version-nb:
    type: int
    default: v1
    description: udm version
  udm-fqdn:
    type: string
    default: oai-udm
    description: udm fqdn
