options:
  image:
    type: string
    default: mysql:5.7
    description: mysql image 
  mysql-port:
    type: int
    default: 3306
    description: mysql service port
  mysqlx-port:
    type: int
    default: 33060
    description: mysqlx service port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  mysql-db:
    type: string
    default: oai_db
    description: oai mysql volume database
  mysql-user:
    type: string
    default: test
    description: mysql user
  mysql-password:
    type: string
    default: test
    description: mysql password
  mysql-root-password:
    type: string
    default: linux
    description: mysql root password
