# Copyright 2022 Ubuntu
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  image:
    type: string
    default: mysql:5.7
    description: mysql image 
  mysql-port:
    type: int
    default: 3306
    description: mysql service port
  mysqlx-port:
    type: int
    default: 33060
    description: mysqlx service port
  time-zone:
    type: string
    default: Europe/Paris
    description: time zone
  mysql-db:
    type: string
    default: oai_db
    description: oai mysql volume database
  mysql-user:
    type: string
    default: test
    description: mysql user
  mysql-password:
    type: string
    default: test
    description: mysql password
  mysql-root-password:
    type: string
    default: linux
    description: mysql root password
